export const PopularCharacters = [
    "Spider-Man",
    "Wolverine",
    "Thor",
    "Cyclops",
    "Iron Man",
    "Daredevil",
    "Hulk",
    "Silver Surfer",
    "Captain America",
    "Thing",
    "Luke Cage",
    "Human Torch",
    "Iron Fist",
    "Nick Fury",
    "Gambit",
    "Hawkeye",
    "Blade",
    "Thunderbolt Ross",
    "Carol Danvers",
    "Sentry",
    "Spider-Woman",
    "Prowler",
    "Nightcrawler",
    "Punisher",
    "Invisible Woman",
    "Iceman",
    "Kaine",
    "Flash Thompson",
    "Ben Reilly",
    "Professor X",
    "Spider-Man 2099",
    "Eddie Brock",
    "Black Cat",
    "Mr. Fantastic",
    "Hank Pym",
    "Storm",
    "Doctor Strange",
    "Colossus",
    "Moon Knight",
    "Angel",
    "Hercules",
    "Kitty Pryde",
    "Miles Morales",
    "Nova",
    "Namor",
    "Beast",
    "Black Panther",
    "Rogue",
    "Captain Marvel",
    "Molten Man",
    "Cloak",
    "Dagger",
    "Mr. Immortal",
    "She-Hulk",
    "Black Widow",
    "Ghost Rider (Blaze)",
    "Bucky Barnes",
    "Captain Britain",
    "Union Jack",
    "Silver Sable",
    "Vision",
    "Cable",
    "Bishop",
    "Havok",
    "Wonder Man",
    "Ant-Man (Lang)",
    "Black Bolt",
    "Quicksilver",
    "Spider-Girl (Parker)",
    "Toxin",
    "Scarlet Witch",
    "Odin",
    "Black Knight",
    "Wasp",
    "Jean Grey",
    "Mockingbird",
    "Lockheed",
    "Noh-Varr",
    "Dum Dum Dugan",
    "X-23",
    "Ka-Zar",
    "Wiccan",
    "Madrox",
    "Elektra",
    "Swordsman",
    "Rick Jones",
    "Hulkling",
    "Patriot",
    "Banshee",
    "Beta Ray Bill",
    "Cassie Lang",
    "Howard the Duck",
    "Speedball",
    "Phil Coulson",
    "War Machine",
    "White Tiger",
    "Prodigy",
    "Squirrel Girl",
    "Jubilee",
    "Emma Frost",
  ];